# Generated by Codex on 2026-02-18

from django.conf import settings
from django.db import migrations


def create_missing_profiles(apps, schema_editor):
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split('.')
    UserModel = apps.get_model(user_app_label, user_model_name)
    UserProfile = apps.get_model('users', 'UserProfile')

    existing_profile_user_ids = UserProfile.objects.values_list('user_id', flat=True)
    missing_user_ids = UserModel.objects.exclude(id__in=existing_profile_user_ids).values_list('id', flat=True)

    pending = []
    for user_id in missing_user_ids.iterator():
        pending.append(UserProfile(user_id=user_id))
        if len(pending) >= 1000:
            UserProfile.objects.bulk_create(pending, batch_size=1000, ignore_conflicts=True)
            pending = []

    if pending:
        UserProfile.objects.bulk_create(pending, batch_size=1000, ignore_conflicts=True)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles, reverse_code=noop_reverse),
    ]
