# Generated by Codex on 2026-02-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_photo'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "CREATE UNIQUE INDEX IF NOT EXISTS users_auth_user_email_ci_unique "
                "ON auth_user (LOWER(email)) "
                "WHERE email <> '';"
            ),
            reverse_sql="DROP INDEX IF EXISTS users_auth_user_email_ci_unique;",
        ),
    ]
