# Generated by Django 5.2.5 on 2026-02-20 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_ci_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hackerrank_profile_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hackerrank_username',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Use 2-50 characters: letters, numbers, dots, underscores, or hyphens.', regex='^[A-Za-z0-9._-]{2,50}$')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leetcode_profile_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leetcode_username',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Use 2-50 characters: letters, numbers, dots, underscores, or hyphens.', regex='^[A-Za-z0-9._-]{2,50}$')]),
        ),
    ]
