# Generated by Django 5.2.5 on 2026-02-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_photo_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hackerrank_profile_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hackerrank_username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='leetcode_profile_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='leetcode_username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='coding_interests',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
